#UTF-8 처리
# msgMeta.properties
SYSTEM000=SYSTEM000,SYSTEM000,1,examdomain,jspeed,msg.cust,msg.dvl,msg.desc,jspeed,20050314205133,jspeed,20050314205133,N,errorPage1,/jsp/errorPage.jsp,ekchoi@itplus.co.kr

ERROR01=ERROR01,ERROR01,0,examdomain,jspeed,msg.cust,msg.dvl,msg.desc,jspeed,20050314200722,jspeed,20050314213816,N,errorPage1,/jsp/errorPage.jsp,ekchoi@itplus.co.kr

