#UTF-8 처리
AML_10_06_01_01.class=org.springframework.web.servlet.view.JstlView
AML_10_06_01_01.url=/Package/AML/AML_10/AML_10_06/AML_10_06_01/AML_10_06_01_01_J.jsp
AML_10_07_01_01.class=org.springframework.web.servlet.view.JstlView
AML_10_07_01_01.url=/Package/AML/AML_10/AML_10_07/AML_10_07_01/AML_10_07_01_01_J.jsp
AML_10_03_01_01.class=org.springframework.web.servlet.view.JstlView
AML_10_03_01_01.url=/Package/AML/AML_10/AML_10_03/AML_10_03_11/AML_10_03_11_01.jsp
AML_10_03_03_01.class=org.springframework.web.servlet.view.JstlView
AML_10_03_03_01.url=/Package/AML/AML_10/AML_10_03/AML_10_03_04/AML_10_03_04_01.jsp

AML_20_01_10_03.class=org.springframework.web.servlet.view.JstlView
AML_20_01_10_03.url=/Package/AML/AML_20/AML_20_01/AML_20_01_10/AML_20_01_10_03_J.jsp