#UTF-8 처리

#============================================================================
# Max get-file-count everytime via FTP  default : 50
#============================================================================

MAX_GET_FILE = 50

#============================================================================
# Directory map making interval (minute)  default : 5
#============================================================================

DIRECTORY_INTERVAL = 3
