#============================================================================
# GTOne JSpeed Query Executor  
#============================================================================
net.sf.jasperreports.query.executer.factory.jspeed=com.gtone.dc.data.ReportQueryExecuterFactory
net.sf.jasperreports.query.executer.factory.JSPEED=com.gtone.dc.data.ReportQueryExecuterFactory
net.sf.jasperreports.jdbc.fetch.size = 500

#============================================================================
# Encoding & Paths
#============================================================================
URL_ENCODING = EUC-KR
REPOGITORY_PATH = /JasperReports/doccenterweb_files
VIEWER_URL = /JasperReports/viewer.jsp

#============================================================================
# Virtualizer Mode (Large File Support)
#
# NONE, FILE_VIRTUALIZER, GZIP_VIRTUALIZER, SWAP_VIRTUALIZER
#============================================================================
DEFAULT_VIRTUALIZER = NONE

#============================================================================
# File Virtualizer
#============================================================================
# maximum size of the paged in cache.
FILE_VIRTUALIZER.MAX_SIZE = 10
# caching directory path
FILE_VIRTUALIZER.DIRECTORY = /JasperReports/doccenterweb_files/temp

#============================================================================
# Gzip Virtualizer
#============================================================================
# maximum size of the paged in cache.
GZIP_VIRTUALIZER.MAX_SIZE = 10

#============================================================================
# Swap Virtualizer
#============================================================================
# maximum size of the paged in cache.
SWAP_VIRTUALIZER.MAX_SIZE = 10
# caching directory
SWAP_VIRTUALIZER.DIRECTORY = /JasperReports/doccenterweb_files/temp
# the size of the blocks allocated by the swap file
SWAP_VIRTUALIZER.BLOCK_SIZE = 2048
# minimum number of blocks by which the swap file grows when full
SWAP_VIRTUALIZER.MIN_GROW_COUNT = 1024
# if true, swap-file deleted when virtualizer dispose
SWAP_VIRTUALIZER.SWAP_OWNER = true