#Main View
managerMain=/amlmanager/page/managerMains.jsp

AXM_LEFT=/amlmanager/page/common/page_str_left.jsp
AXM_LEFT_MNG=/amlmanager/page/common/page_mng_left.jsp
AXM_RIGHT=/amlmanager/page/common/page_str_right.jsp
AXM_HTML=/amlmanager/page/common/page_html_tmpl_pop.jsp
AXM_TMPL=/amlmanager/page/common/page_tmpl_pop.jsp
AXM_ERR_LIST=/amlmanager/page/common/page_err_list_pop.jsp

AXM_10_01=/amlmanager/page/STR/AXM_10_01.jsp
AXM_10_02=/amlmanager/page/STR/AXM_10_02.jsp
AXM_10_03=/amlmanager/page/STR/AXM_10_03.jsp
AXM_10_04=/amlmanager/page/STR/AXM_10_04.jsp
AXM_10_05=/amlmanager/page/STR/AXM_10_05.jsp
AXM_10_06=/amlmanager/page/STR/AXM_10_06.jsp
AXM_10_07=/amlmanager/page/STR/AXM_10_07.jsp
AXM_10_08=/amlmanager/page/STR/AXM_10_08.jsp
AXM_10_09=/amlmanager/page/STR/AXM_10_09.jsp
AXM_10_10=/amlmanager/page/STR/AXM_10_10.jsp

AXM_10_01_01=/amlmanager/page/STR/AXM_10_01_01.jsp
AXM_10_01_02=/amlmanager/page/STR/AXM_10_01_02.jsp
AXM_10_01_03=/amlmanager/page/STR/AXM_10_01_03.jsp
AXM_10_01_04=/amlmanager/page/STR/AXM_10_01_04.jsp

AXM_20_01=/amlmanager/page/CTR/AXM_20_01.jsp
AXM_20_01_01=/amlmanager/page/CTR/AXM_20_01_01.jsp

AXM_30_01=/amlmanager/page/RB/AXM_30_01.jsp
AXM_30_02=/amlmanager/page/RB/AXM_30_02.jsp

AXM_40_01=/amlmanager/page/TOOL/AXM_40_01.jsp
AXM_40_02=/amlmanager/page/TOOL/AXM_40_02.jsp
AXM_40_03=/amlmanager/page/TOOL/AXM_40_03.jsp
AXM_40_04=/amlmanager/page/TOOL/AXM_40_04.jsp
AXM_40_04_01=/amlmanager/page/TOOL/AXM_40_04_01.jsp
AXM_40_05=/amlmanager/page/TOOL/AXM_40_05.jsp
AXM_40_06=/amlmanager/page/TOOL/AXM_40_06.jsp
AXM_40_07=/amlmanager/page/TOOL/AXM_40_07.jsp