#20240318 FILE PATH 파일업로드 및 다운로드, STR, CTR
#BASE_DIR=/data/download/
##삼성증권##
BASE_DIR=C:/rbashared/upload/

SERVER_TYPE=LOCAL

##삼성증권##

SITE_NAME=gtone
# =====================================


# =====================================
# =====================================
#LOGIN_TYPE
LOGIN_TYPE = SESSION
#LOGIN_TYPE = COOKIE
# =====================================

#Common Grid Header Path Information
#type 별 그리드 경로
#GRID_HEADER_PATH=/Package/ext/header/aml,/Package/ext/header/rba/type01
#GRID_HEADER_PATH=/Package/ext/header/aml,/Package/ext/header/rba/type02
GRID_HEADER_PATH=/Package/ext/header/aml,/Package/ext/header/rba/type03,/Package/ext/header/rba/Kofiu
#GRID_HEADER_PATH=/Package/ext/header/aml,/Package/ext/header/rba/type07,/Package/ext/header/rba/Kofiu
#GRID_HEADER_PATH=/Package/ext/header/aml,/Package/ext/header/rba/type04,/Package/ext/header/rba/Kofiu

#Action Class Prefix


#Message Group Idetification
MESSAGE_GROUP_ID=AMLG

#Search Engine Properties (term unit : second)
SEARCH_INDEX_DIR=/Package/ext/search/index
SEARCH_INDEX_CLASS=com.gtone.aml.admin.search.CollectQuery


#Message Bundle Properties
FILE_NAME=messages-express.properties


LOCALE1=ko, ja, en, zh
LOCALE2=ko_KR, ja_JP, en_US, zh_CN
LOCALE3=ko-KR, ja-JP, en-US, zh-CN

# XML Configuration
AP_SERVER_CTR_TEMP_FILE=ctr_template.xlsx
AP_SERVER_CTR_INIT_FILE=ctr_template_init.xlsx
AP_SERVER_CTR_COMP_FILE=ctr_complete.xlsx

# XML Configuration (삼성증권)
AP_SERVER_STR_FILE_PATH=/rbashared/upload/tms/kofiu/exported/xml/
AP_SERVER_CTR_FILE_PATH=/rbashared/upload/tms/kofiu/exported/snd/

# Export Document Configuration
CUSTOMER_DOCBASE_YYYY = 2009
CUSTOMER_DOCBASE_SN = 10001

# CTR Export Document Configuration
CTR_CUSTOMER_DOCBASE_YYYY = 2009
CTR_CUSTOMER_DOCBASE_SN = 10001
CTR_EXPORT_FILE = SND

#[START] WX4AML에서 사용하지 않는 KEY 목록
# WATCHLIST_ENG_CLASSNAME
#WATCHLIST_EXTRA_FIELD=SQ,RNM_CNFR_CCD,RNMCNO,HNDL_DY_TM,WL_BIRTHDAY,INDV_CORP_CCD,ORG_NM
#WATCHLIST_EXTRA_FIELD_KEYWORD=WC_LIST_CCD,ADDR,NTN_NM,SWIFT,NTN_CD

#20180702 WatchList 이력 기능 추가


#WATCHLIST_FILTER_CLASSNAME=com.gtone.aml.tis.TrilliumWatchListFilter
#[END] WX4AML에서 사용하지 않는 KEY 목록


##삼성증권##
#WATCHLIST_INDEX_DIR=/rbashared/watchlist/index/
WATCHLIST_INDEX_DIR=C:/AMLSource/workspace/rbashared/index/
WATCHLIST_EXTRA_FIELD=SQ,RNM_CNFR_CCD,RNMCNO,HNDL_DY_TM,WL_BIRTHDAY,INDV_CORP_CCD,ORG_NM
WATCHLIST_EXTRA_FIELD_KEYWORD=WC_LIST_CCD,ADDR,NTN_NM,SWIFT,NTN_CD
WATCHLIST_OR_FIELD=CS_NM,WC_LIST_CCD,ADDR,NTN_NM,SWIFT
WATCHLIST_EXTRA_FIELD1=MNG_SNO,RNM_CNFR_CCD,RNMCNO,HNDL_DY_TM,WL_BIRTHDAY,INDV_CORP_CCD,ORG_NM,WL_REG_DT
WATCHLIST_EXTRA_FIELD_KEYWORD1=WC_LIST_CCD,ADDR,NTN_NM,SWIFT,NTN_CD,WL_REG_DT
WATCHLIST_OR_FIELD1=CS_NM,WC_LIST_CCD,ADDR,NTN_NM,SWIFT,WL_REG_DT
##삼성증권##

##7.4##
# WX4AML_WATCHLIST (KYE, WLF에서 공통으로 사용)
#WATCHLIST_INDEX_DIR=D:/AMLXpress/watchlist/index/
#WATCHLIST_INDEX_DIR=C:/AMLSource/workspace/watchlist/index
#WATCHLIST_IDX_CLASSNAME=com.gtone.aml.watchlist.index.WatchIndexWriter
#WATCHLIST_EXTRA_FIELD=WC_LIST_CCD,SQ,WC_UID,CS_NM,ADDR,INDV_CORP_CCD,CS_NM_FIRST,CS_NM_LAST,CS_NM_MIDDLE,BIC_NO,CS_NM_ORG,SEX,CATEGORY,HNDL_DY_TM,REG_DT,NM_TYPE,NTN_CD_N,DOB_N,FURTHER_INFORMATION1_N,ACTIVE_STATUS,WC_GRP_LIST_CCD,IMO_NO,IN_ACTIVE_PEP
#WATCHLIST_EXTRA_FIELD_KEYWORD=WC_LIST_CCD,WC_UID,IMO_NO,BIC_NO
#COUNTRY_INDEX_CODE=ko,zh,ja,ar,bg,bn,br,ca,cn,cz,da,de,el,es,et,eu,fa,fi,fr,ga,gl,ji,hu,id,it,lt,lv,nl,no,ro,ru,so,sv,th,tr
#WATCHLIST_LOCAL_FIELD=WC_LIST_CCD,SQ,WC_UID,WC_GRP_LIST_CCD,CS_NM,CS_NM_ORG,INDV_CORP_CCD,NTN_CD_N,SEX,DOB_N,ADDR,RNMCNO

#WACTHLIST_STOPWORDS=holding,professor,fka,aka,initials,limited,industry,www,com,the,headquarters,intelligence,abc,abu,wearform,general,corporation
WACTHLIST_STOPWORDS=

#Watchlist 등록(자체리스트포함) 결재기능 사용 여부
WL_APPR_YN=Y

MAXROWS=100
LOCALIDXPATH=local
DAILYIDXPATH=daily
FULLIDXPATH=WPEP01
#색인에 추가할 대상 필드 [ NTN_CD(국가), DOB(생년월일), SEX(성별), INDV_CORP_CCD(개인법인구분코드),NOT(4개항목을 추가안함)]
#INDEX_FIELD=NTN_CD,DOB,SEX,INDV_CORP_CCD
INDEX_FIELD=NOT

#20191203 watchlist변경분 사용여부 - 웹프로젝트는 aml_config.properties에서 관리하지만 WALB수행시 WAS관계를 끊으면서 배치프로젝트에 추가된 express.properties에 통합시킴
AMLWatchList_change_registration=Y


SEARCH_ANALYZER_CLASSNAME = org.apache.lucene.analysis.SimpleAnalyzer

####### External Scheduler
#REMOTE_SCHEDULER_IP=127.0.0.1
#REMOTE_SCHEDULER_PORT=4444

#RBA_REPORT_EXCEL_FILE=d:/


####### RBA TEMPLATE FILE PATH
#LOCAL
#RBA_TEMPLATE_EXCEL_FILE=d:/template
#REAL
#RBA_TEMPLATE_EXCEL_FILE=/template


#삼성증권#
RBA_REPORT_EXCEL_FILE=/rbashared/upload/kofiu
RBA_TEMPLATE_EXCEL_FILE=/rbashared/upload/tongje

WAS_URL=http://localhost:8080
CNF_URI=/express.do?viewName=/Kernel/express/header/getGridConfig.jsp

FW_VER=5.0

#20171122, dynamic grid header printable for BRMiner
PRINTABLE_DYNAMIC_GRID=N

####20180529, RBA_type03(KPMG) RBA위험평가결과보고서 템플릿파일경로  (WEBCONTENT경로에 맞게 수정)
RBA_KPMG_FILE_PATH=/home/aml/AML70/WebContent/download/RBA/type03/
#RBA_KPMG_FILE_PATH=D:/workspace/AMLXpress_7/AMLXpress_7/WebContent/download/RBA/type03/
#RBA_KPMG_INIT_FILE=RBA_Report_Init.xlsx
RBA_KPMG_INIT_FILE=RBA_Report_Init.xlsx
RBA_KPMG_TEMP_FILE=RBA_Report_Temp.xlsx
RBA_KPMG_COMP_FILE=RBA_Report.xlsx

# BRMiner Env Start
##Rule 수정시 필수로 사유 등록여부
REQUESTOR_MANDATORY = N
## Rule grid combocount
TEMPLATE_COMBO_COUNT = 3

## API_VERSION : RAPI5J.jar
API_VERSION = 5.0
PROD_MENU_ENABLED =N
ENCODING =N
#KEY_DATA_PATH = /home/aml/RuleServer/Bin
ENCRYPTION = AES128

##BRS120TB 정보 사용 하지 않는 옵션
RULEMODE=AML
##연관맵 옵션(BRMiner.Studio)
MART_RULE_DAO_CLASSNAME=com.gtone.aml.admin.dao.AMLMartRuleDAO
## PRODUCT_FACTORY FOR KBIZ
ANALYSIS_MENU_ENABLED =N
REPORTCENTER_ENABLED =N
##토스용 모델 추출기준관리
RULE_MODEL_MANAGE_ENABLED =N

# SCHEDULER (MODE:on/off)
SCHEDULE_MODE=off
SCHEDULE_LOADER=com.gtone.aml.common.schedule.ScheduleLoader
#STARTUP_CLASS=
 
#WAS LOG에서만 ******** 변환할 [키 구분자 ,] 빈값이면 체크안함
LOG_CHANGE_KEY=


PROJECT_GUBN=WAS

#AMLAISTROpinion
toLLM_Socket_IP=172.16.15.112
toLLM_Socket_Port=9999
