# 중계기관코드(금융투자협회->한국증권업협회)
RLY_FCLT_CD=CA0002

# GPKI암호키분배용 인증서경로
GPKI_CERT_PATH=/appdata/rba/kofiu_cert/cert/gpki/SVR1160131005_env.cer
# 암호화 알고리즘
GPKI_ALGORITHM=ARIA
# 라이센스 경로
LICENSE_PATH=/appdata/rba/kofiu_cert/license.kica
# 인증서 경로
CERT_PATH=/appdata/rba/kofiu_cert/cert/npki/signCert.der
# 인증서 개인키 경로
CERT_KEY_PATH=/appdata/rba/kofiu_cert/cert/npki/signPri.key
# 인증서 비밀번호 (Base64Util encryption)
CERT_PASSWD=IXEydzNlNHI1dA==
#CERT_PASSWD=amVvbmcyMzYwIQ==
# 전자서명 SHELL 파일 경로
CERT_SHELL_PATH=/app/rba/AMLExpress7/AMLExpres7.4_Batch/dist/KofiuSignUtil.sh
# GPKI conf 및 lic 경로. (04.GPKI conf)
GPKI_CONF_PATH=/appdata/rba/kofiu_cert/conf

# 뱅킹대외계 개발
SFTP_SEND_IP=45.219.31.20
SFTP_SEND_PORT=19042
SFTP_SEND_ID=fiuS
# password seed encryption
# SFTP_SEND_PW=iLPTY0dWO/6xEAqUcJilBw==
 SFTP_SEND_PW=c2NwMDMw
SFTP_SEND_DIR=/tanylink/batch_file/fiu/send

SFTP_RECV_DIR=/rbashared/upload/tms/kofiu/tmsrcv