#UTF-8처리
erwin=com.itplus.mm.server.collector.adapter.model.erwin.ERWin4Adapter

Schema.default=com.itplus.mm.server.collector.adapter.db.QueryJDBCAdapter

modelmart=com.itplus.mm.server.collector.adapter.model.UDPQueryAdapter

erstudio=com.itplus.mm.server.collector.adapter.model.erstudio.Erstudio4Adapter

Model.default=com.itplus.mm.server.collector.adapter.model.UDPQueryAdapter

sa=com.itplus.mm.server.collector.adapter.model.sa.SAAdapter

cm=com.itplus.mm.server.collector.adapter.application.cm.CMAdapter

