#jspeed
pageFirstImage=Kernel/ext/images/bullet_first.gif
pageLastImage=Kernel/ext/images/bullet_last.gif
pagePrevImage=Kernel/ext/images/bullet_prev.gif
pageNextImage=Kernel/ext/images/bullet_next.gif
pageRowPerPage=10
pageBlock=10

init_menuID=AML_00

init_pageID=AML_00_02_01_01

dateFormat=yyyy-MM-dd

##File Extensions Setting
upload.file=xls,xlsx,ppt,pptx,doc,docx,zip,pdf,txt,hwp,jpg,jpeg,gif,png,csv,xml
upload.file.x=xlsx,xls
upload.file.xls=xls
upload.file.z=zip,xml
upload.file.zip=zip
upload.file.m=docx,pdf
upload.file.r=jpg,jpeg,gif,png,xlsx,xls,ppt,pptx

PKG_ID=6

auth.check.YN=Y

branchMaxLength=3

MoneyType=KRW

AmlTitle=AMLXpress

#STR : 00전체(R&D)-ALL, 01은행-BANK, 02증권-STOCK, 03보험-INSURANCE, 04카드-CARD,05카지노-CASINO, 06가상자산-CRYPTO, 07전자금융
amlType=02

CIFMaxLength=8
# Max-get-file count (default : 50)
MAX_GET_FILES = 70

# Max get file size KB ( 0: every file)
MAX_FILE_SIZE = 1024

#20170511 popup no check session
popupNoCheckpage=
popupNoCheckpageUser=admin

PKG_NAME=AML
#[ 여기서부터가 5.0 시작 ] -- 단, 4.0 에도 존재할 수 있음 --------------------------------------

#rbaType: type01(able)/type02(pwc)/type03(kpmg)/type07(able:카카오,부동산신탁)/type04(RBA Lite Ver)
rbaType=type03

#20171018, IE Compatible mode: 5, 7, 8, 9, 10, 11 and Edge
IE_COMPATIBLE_MODE=Edge

# 20130627 -> 20171113, Y: Encrypt, N: None Encrypt, R: Reverse
#20171121, when masking, use hidden field
#Y: field_cipher_YN=Y - decoded data, field_cipher_YN=R - encoded data, field_cipher_YN=N - ignore
#N: not available
field_cipher_YN=Y

#20171113, masking process
FIELD_MASK_YN=Y
MASK_SYMBOL=*

FIELD_MASK_USE_HIDDEN=N

#20171123
# login type (JSPEED, LDAP, SSO, ..., etc)
LOGIN_TYPE=JSPEED
#LOGIN_TYPE=LDAP
# LDAP server IP
LDAP_DOMAIN=127.0.0.1:9093
# LDAP Factory
LDAP_FACTORY=com.sun.jndi.ldap.LdapCtxFactory
#LDAP_FACTORY=com.ibm.jndi.LDAPCtxFactory
LDAP_IMPL=com.gtone.aml.user.LoginLDAPImpl

#20171204
#사용자 별로 권한 여부 체크 후 javascript 함수를 호출하는 기능 사용 여부, Y: USE, N: UNUSE
USER_AUTH_USE=N
#사용자 별로 권한 여부 체크 후 호출되는 javascript 함수명
USER_AUTH_FUNC=

#20171206
#DB2 에서 SELECT 문의 쿼리에서 마지막에 WITH UR 처리 사용 여부
#쿼리문을 서버에서 동적으로 조립할때 사용함
DB2_WITH_UR_USE_YN=N

#20171208
#overlay 사용여부
OVERLAY_USE_YN=Y

#20171212, 로그를 디비에 저장하는 QueryID 설정
LOG_QUERY_ID=insertLogDB

#20171213, jquery 경로
JQUERY_PATH=/Kernel/ext/devx/20.2/js/jquery.min.js

#20171214, 공통함수를 이용하여 통신할 경우 '' 값을 null 로 치환해주는 기능의 활성 여부, 주로 DB2 에서 필요한 기능인데 퍼포먼스에 영항을 미치기 때문에 가급적 사용 안하는게 바람직 함
EMPTY_TO_NULL=N

#20180125, 메인화면 차트의 실데이터 사용여부
MAIN_DASHBOARD_CHART_REAL_DATA_YN=N

#20180131, 그리드 헤더명 화살표 표시 여부
GRID_MODIFY_DISPLAY=N

#20180206, BR(룰) 관련 화면의 왼쪽 메뉴 가로 사이즈
BR_MENU_WIDTH=280

#20180206, 로그인시 최초 또는 주기적  패스워드 변경 방식, 0: 변경 안함, 1: 최초 한번, N>1: N일 마다 변경
CHANGE_PWD_TYPE=0
#20180206, 최초 또는 주기적  패스워드 변경을 스킵했을때 대응 방식, 'LOGOUT': 강제로 로그 아웃 시킴, 'REPETITION': 로그인 할때마다 반복적으로 패스워드 변경 권유
CHANGE_PWD_SKIP=LOGOUT

#20180221, Content-Security-Policy 헤더 설정
CONTENT_SECURITY_POLICY=default-src http: 'unsafe-inline' 'unsafe-eval';
#20180221, X_CONTENT_TYPE_OPTIONS 헤더 설정
X_CONTENT_TYPE_OPTIONS=nosniff
#20180221, X_XSS_PROTECTION 헤더 설정
X_XSS_PROTECTION=1
#20180221, STRICT_TRANSPORT_SECURITY 헤더 설정
STRICT_TRANSPORT_SECURITY=max-age=31536000; includeSubDomains; preload
#20180221, X_FRAME_OPTIONS 헤더 설정
X_FRAME_OPTIONS=SAMEORIGIN
#20180225, X_XSS 체크 헤더 설정
xss_check_YN=N
#20180225, 링크가 있는 셀 밑줄 설정
LINK_UNDERLINE=N

#20180326
#사용자 별로 암복호화 및 마스킹 예외권한 여부 체크 후 기능 사용 여부, Y: USE, N: UNUSE
CME_USER_AUTH_USE=N

#20181109 AML Log Table Save Option(Y : insert, N : Pass)
AMLlogSaveOption=Y
#AMLlogSaveFilePath=D:/log/
#20191108 AML Login 성공/실패 여부에 따라 이력이 저장된다
AMLloginSuccFail=Y

#20190613 MYSQL 사용여부
DB_MYSQL_YN=N
#20210602 DBType 설정 : ORACLE, MYSQL, POSTGRE
DBTYPE=ORACLE

#SQL Injection 특수문자 특수구분 필터링 기능
SQL_INJECTION_YN=N
#AML로그인 시 장기 미사용자 검증 시 사용(미사용기간설정 : 90일)
LAST_LOGIN_CHK=90

#2023.02.06 구글OTP사용여부(Y/N으로 설정)
OTP_USE_YN=N
#QR코드 이미지 내부생성 여부 Y/N
OTP_IN=Y

#2023-06-15 byun STR 임의보고 빈계좌 생성시 계좌번호
STR_KYC_ALERT_EMPTY_AC_NO=99999999

#톰캣로그경로(웹)
WAS_LOG_PATH=/home/aml/AML70/apache-tomcat-8.5.5/logs/
WAS_LOG_NAME=catalina.out

SESSION_ALLOW_PAGE_ID=googleotp,otpLogin,OSSList

#공개 데이터 여부  Y:기관 공개 데이터 N:다운존스 상용 데이터
WL_OPEN_DATA_YN=N

### Batch Config
#BATCH_HOME=http://localhost:9090/mart/v1/RunJob
#BATCH_HOME_BIN=../amlxpress-batch-app/bin
BATCH_HOME_BIN=/home/aml/AML70/AMLXpress_7_Batch/dist
BATCH_SCRIPT=ExecuteBatch

BATCH_URL=http://172.16.15.15:9950/api/v1/aml/batch/execute
CONNECT_TIME_OUT=10
READ_TIME_OUT=15

#batch_sys_mode = BATCH or REST
batch_sys_mode=BATCH

#RA > 결재버튼 : Y, 적용버튼 : N
RA_APPR_YN=Y

##TAB Count Setting - 숫자 설정 (0 또는 값을 설정하지 않으면 무제한으로 설정)
TAB_COUNT_SET=0

useBRMiner=N

#DBCharset
#[UTF-8]
#Oracle : AL32UTF8, UTF8 || MySQL : utf8mb4, utf8 || PostgreSQL : UTF8
#[EUC-KR]
#Oracle : KO16KSC5601    || MySQL : euckr         || PostgreSQL : EUC_KR
DBEncoding=UTF-8
SPLIT_MAX_LENGTH=3900


#삼성증권
uploadPath.tms=/rbashared/upload/tms/
uploadPath.report.temp=/rbashared/upload/report/temp
uploadPath.notice=/rbashared/upload/notice

# KPIC InternalControl Edu File DIR
uploadPath.edu=/rbashared/upload/edu
# KPIC InternalControl EXPN File DIR
uploadPath.expn=/rbashared/upload/expn
# KPIC InternalControl EXMS File DIR
uploadPath.exms=/rbashared/upload/exms
# KPIC InternalControl EXCD CheckList File DIR
uploadPath.excd=/rbashared/upload/excd
