#UTF-8 처리

BRANCH_RANGE=000,A990

BRANCH_EX_LIST=NO

BRANCH_EX_NOT_LIST=580,560

MASTER_ROLE=4,5,7,104,105

TEAM_LEADER_BRANCH_Y_ROLE_ID=6

TEAM_LEADER_HEAD_N_ROLE_ID=4

TEAM_LEADER_BRANCH_N_ROLE_ID=3

TEAM_LEADER_HEAD_Y_ROLE_ID=5,9,7

USER_BRANCH=3,6

