CS_NO=com.gtone.aml.dao.common.AMLFieldSeedCipher
#EMAIL=com.gtone.aml.dao.common.AMLFieldSeedCipher
ACNT_NO=com.gtone.aml.dao.common.AMLFieldSeedCipher
#RNMCNO=com.gtone.aml.dao.common.AMLFieldSeedCipher
BSMN_RNO=com.gtone.aml.dao.common.AMLFieldSeedCipher
#TableId[C_PAGE_SVC_LOG-PARAM_VAL]
PARAM_VAL=com.gtone.aml.dao.common.AMLFieldSeedCipher
AFPR_NO=com.gtone.aml.dao.common.AMLFieldSeedCipher