#실명번호
CS_NO=com.gtone.aml.dao.common.AMLFieldSeedCipher
CS_NO_VIEW=com.gtone.aml.dao.common.AMLFieldSeedCipher
CS_NO_DEC=com.gtone.aml.dao.common.AMLFieldSeedCipher
PRXY_CS_NO=com.gtone.aml.dao.common.AMLFieldSeedCipher
GNL_PRXY_CS_NO=com.gtone.aml.dao.common.AMLFieldSeedCipher
BSMN_RNO=com.gtone.aml.dao.common.AMLFieldSeedCipher
REALNUMBERCONFIRM=com.gtone.aml.dao.common.AMLFieldSeedCipher
REALNUMBER=com.gtone.aml.dao.common.AMLFieldSeedCipher
BIZNO=com.gtone.aml.dao.common.AMLFieldSeedCipher
ACCOUNTUSER=com.gtone.aml.dao.common.AMLFieldSeedCipher
AGENTUSER=com.gtone.aml.dao.common.AMLFieldSeedCipher
AFPR_NO=com.gtone.aml.dao.common.AMLFieldSeedCipher
#계좌번호
ACNT_NO=com.gtone.aml.dao.common.AMLFieldSeedCipher
ACNT_NO_DEC=com.gtone.aml.dao.common.AMLFieldSeedCipher
GNL_AC_NO_VIEW=com.gtone.aml.dao.common.AMLFieldSeedCipher
CPRTY_TRSNS_AC_NO=com.gtone.aml.dao.common.AMLFieldSeedCipher
ACCOUNTNUMBER=com.gtone.aml.dao.common.AMLFieldSeedCipher
#email
EMAIL_ID=com.gtone.aml.dao.common.AMLFieldSeedCipher
EMAIL_HOST_NAME=com.gtone.aml.dao.common.AMLFieldSeedCipher
#연락처
CNTY_NATI_CRYP=com.gtone.aml.dao.common.AMLFieldSeedCipher
CNTY_AREA_CRYP=com.gtone.aml.dao.common.AMLFieldSeedCipher
CNTY_ECNO_CRYP=com.gtone.aml.dao.common.AMLFieldSeedCipher
CNTY_NO_CRYP=com.gtone.aml.dao.common.AMLFieldSeedCipher
DL_P_HSE_NATI=com.gtone.aml.dao.common.AMLFieldSeedCipher
DL_P_HSE_AREA=com.gtone.aml.dao.common.AMLFieldSeedCipher
DL_P_HSE_ECNO=com.gtone.aml.dao.common.AMLFieldSeedCipher
DL_P_HSE_NO=com.gtone.aml.dao.common.AMLFieldSeedCipher
DL_P_MBL_NATI=com.gtone.aml.dao.common.AMLFieldSeedCipher
DL_P_MBL_AREA=com.gtone.aml.dao.common.AMLFieldSeedCipher
DL_P_MBL_ECNO=com.gtone.aml.dao.common.AMLFieldSeedCipher
DL_P_MBL_NO=com.gtone.aml.dao.common.AMLFieldSeedCipher
HD_BRNCH_NATI=com.gtone.aml.dao.common.AMLFieldSeedCipher
HD_BRNCH_AREA=com.gtone.aml.dao.common.AMLFieldSeedCipher
HD_BRNCH_ECNO=com.gtone.aml.dao.common.AMLFieldSeedCipher
HD_BRNCH_NO=com.gtone.aml.dao.common.AMLFieldSeedCipher
BSNS_CMPNY_NATI=com.gtone.aml.dao.common.AMLFieldSeedCipher
BSNS_CMPNY_AREA=com.gtone.aml.dao.common.AMLFieldSeedCipher
BSNS_CMPNY_ECNO=com.gtone.aml.dao.common.AMLFieldSeedCipher
BSNS_CMPNY_NO=com.gtone.aml.dao.common.AMLFieldSeedCipher
PRXY_NATI=com.gtone.aml.dao.common.AMLFieldSeedCipher
PRXY_AREA=com.gtone.aml.dao.common.AMLFieldSeedCipher
PRXY_ECNO=com.gtone.aml.dao.common.AMLFieldSeedCipher
PRXY_NO=com.gtone.aml.dao.common.AMLFieldSeedCipher
PRXY_CNTY_NATI_CRYP=com.gtone.aml.dao.common.AMLFieldSeedCipher
PRXY_CNTY_AREA_CRYP=com.gtone.aml.dao.common.AMLFieldSeedCipher
PRXY_CNTY_ECNO_CRYP=com.gtone.aml.dao.common.AMLFieldSeedCipher
PRXY_CNTY_NO_CRYP=com.gtone.aml.dao.common.AMLFieldSeedCipher
PHONEHANDPHONE_NATI=com.gtone.aml.dao.common.AMLFieldSeedCipher
PHONEHANDPHONE_AREA=com.gtone.aml.dao.common.AMLFieldSeedCipher
PHONEHANDPHONE_ECNO=com.gtone.aml.dao.common.AMLFieldSeedCipher
PHONEHANDPHONE_NO=com.gtone.aml.dao.common.AMLFieldSeedCipher
PHONE_NATI=com.gtone.aml.dao.common.AMLFieldSeedCipher
PHONE_AREA=com.gtone.aml.dao.common.AMLFieldSeedCipher
PHONE_ECNO=com.gtone.aml.dao.common.AMLFieldSeedCipher
PHONE_NO=com.gtone.aml.dao.common.AMLFieldSeedCipher
BIZTELNO_NATI=com.gtone.aml.dao.common.AMLFieldSeedCipher
BIZTELNO_AREA=com.gtone.aml.dao.common.AMLFieldSeedCipher
BIZTELNO_ECNO=com.gtone.aml.dao.common.AMLFieldSeedCipher
BIZTELNO_NO=com.gtone.aml.dao.common.AMLFieldSeedCipher
TEL1_0_CRYP=com.gtone.aml.dao.common.AMLFieldSeedCipher
TEL1_1_CRYP=com.gtone.aml.dao.common.AMLFieldSeedCipher
TEL1_2_CRYP=com.gtone.aml.dao.common.AMLFieldSeedCipher
TEL1_3_CRYP=com.gtone.aml.dao.common.AMLFieldSeedCipher
TEL2_0_CRYP=com.gtone.aml.dao.common.AMLFieldSeedCipher
TEL2_1_CRYP=com.gtone.aml.dao.common.AMLFieldSeedCipher
TEL2_2_CRYP=com.gtone.aml.dao.common.AMLFieldSeedCipher
TEL2_3_CRYP=com.gtone.aml.dao.common.AMLFieldSeedCipher
MOB_0_CRYP=com.gtone.aml.dao.common.AMLFieldSeedCipher
MOB_1_CRYP=com.gtone.aml.dao.common.AMLFieldSeedCipher
MOB_2_CRYP=com.gtone.aml.dao.common.AMLFieldSeedCipher
MOB_3_CRYP=com.gtone.aml.dao.common.AMLFieldSeedCipher
#주소
BSC_ADDR=com.gtone.aml.dao.common.AMLFieldSeedCipher
DNG_FLWG_ADDR=com.gtone.aml.dao.common.AMLFieldSeedCipher
DL_P_HSE_BSC_ADDR=com.gtone.aml.dao.common.AMLFieldSeedCipher
DL_P_HSE_DNG_ADDR=com.gtone.aml.dao.common.AMLFieldSeedCipher
DL_P_WP_BSC_ADDR=com.gtone.aml.dao.common.AMLFieldSeedCipher
DL_P_WP_DNG_ADDR=com.gtone.aml.dao.common.AMLFieldSeedCipher
HD_BRNCH_BSC_ADDR=com.gtone.aml.dao.common.AMLFieldSeedCipher
HD_BRNCH_DNG_ADDR=com.gtone.aml.dao.common.AMLFieldSeedCipher
BSNS_CMPNY_BSC_ADDR=com.gtone.aml.dao.common.AMLFieldSeedCipher
BSNS_CMPNY_DNG_ADDR=com.gtone.aml.dao.common.AMLFieldSeedCipher
ADDRESS_BSC=com.gtone.aml.dao.common.AMLFieldSeedCipher
ADDRESS_DNG=com.gtone.aml.dao.common.AMLFieldSeedCipher
ADDRESSCOMPANY_BSC=com.gtone.aml.dao.common.AMLFieldSeedCipher
ADDRESSCOMPANY_DNG=com.gtone.aml.dao.common.AMLFieldSeedCipher
BIZADDRESS_BSC=com.gtone.aml.dao.common.AMLFieldSeedCipher
BIZADDRESS_DNG=com.gtone.aml.dao.common.AMLFieldSeedCipher
ADDR_PS_BSC=com.gtone.aml.dao.common.AMLFieldSeedCipher
ADDR_PS_DTL=com.gtone.aml.dao.common.AMLFieldSeedCipher
ADDR_OF_BSC=com.gtone.aml.dao.common.AMLFieldSeedCipher
ADDR_OF_DTL=com.gtone.aml.dao.common.AMLFieldSeedCipher
ADDR_HQ_BSC=com.gtone.aml.dao.common.AMLFieldSeedCipher
ADDR_HQ_DTL=com.gtone.aml.dao.common.AMLFieldSeedCipher
ADDR_BN_BSC=com.gtone.aml.dao.common.AMLFieldSeedCipher
ADDR_BN_DTL=com.gtone.aml.dao.common.AMLFieldSeedCipher
#RBA SAMPLING
DATA05=com.gtone.aml.dao.common.AMLFieldSeedCipher
DATA10=com.gtone.aml.dao.common.AMLFieldSeedCipher
#RBA EMAIL
REMAIL=com.gtone.aml.dao.common.AMLFieldSeedCipher
BEMAIL=com.gtone.aml.dao.common.AMLFieldSeedCipher
#Watch list search_Result
PSPT_NO=com.gtone.aml.dao.common.AMLFieldSeedCipher
PASSPORTNO=com.gtone.aml.dao.common.AMLFieldSeedCipher
#User call_log
SQL_PRMTR_VAL=com.gtone.aml.dao.common.AMLFieldSeedCipher
CORPNO=com.gtone.aml.dao.common.AMLFieldSeedCipher
PRINCIPALUSER=com.gtone.aml.dao.common.AMLFieldSeedCipher
PARTICIPANTUSER=com.gtone.aml.dao.common.AMLFieldSeedCipher
DL_PRXY_CS_NO=com.gtone.aml.dao.common.AMLFieldSeedCipher
CPRTY_TRSNS_AC_RNM_NO=com.gtone.aml.dao.common.AMLFieldSeedCipher