#UTF-8 처리

INST_FINISHED_DT=yyyy-MM-dd HH:mm:ss

LAST_END_DT=yyyy-MM-dd HH:mm:ss

ST_DT=yyyy-MM-dd HH:mm:ss

NEXT_FIRE_DATE=yyyy-MM-dd HH:mm:ss

PROC_START_DT=yyyy-MM-dd HH:mm:ss

INST_START_DT=yyyy-MM-dd HH:mm:ss

REQ_DT=yyyy-MM-dd HH:mm:ss

LAST_START_DT=yyyy-MM-dd HH:mm:ss

DEPLOY_DT=yyyy-MM-dd HH:mm:ss

LAST_MODIFY_DATE=yyyy-MM-dd

PROC_DUE_DT=yyyy-MM-dd HH:mm:ss

END_DT=yyyy-MM-dd HH:mm:ss

SCHD_APPLY_START_DT=yyyy-MM-dd HH:mm:ss

UPD_DT=yyyy-MM-dd HH:mm:ss

SCHD_APPLY_END_DT=yyyy-MM-dd HH:mm:ss

START_DT=yyyy-MM-dd HH:mm:ss

NEXT_FIRE_DT=yyyy-MM-dd HH:mm:ss

CRE_DT=yyyy-MM-dd HH:mm:ss

APPR_DT=yyyy-MM-dd HH:mm:ss

