#UTF-8 처리

db2=com.ibm.db2.jcc.DB2Driver

as400=com.ibm.as400.access.AS400JDBCDriver

unisql=unisql.jdbc.driver.UniSQLDriver

odbc=sun.jdbc.odbc.JdbcOdbcDriver

microsoft=com.microsoft.sqlserver.jdbc.SQLServerDriver

informix-sqli=com.informix.jdbc.IfxDriver

sqlserver=com.microsoft.sqlserver.jdbc.SQLServerDriver

informix-sql=com.informix.jdbc.IfxDriver

mysql=org.git.mm.mysql.Driver

oracle=oracle.jdbc.driver.OracleDriver

msql=com.imaginary.sql.msql.MsqlDriver

sybase=com.sybase.jdbc2.jdbc.SybDriver

Altibase=Altibase.jdbc.driver.AltibaseDriver
