#UTF-8 처리

db2=SYSTOOLS,SYSSTAT,SYSPROC,SYSIBM,SYSFUN,SYSCAT,SQLJ,NULLID

informix=sysmaster,sysuser,sysutils

sqlserver=master,msdb,pubs,Northwind,tempdb,model

oracle=ORDSYS,ORDPLUGINS,MDSYS,CTXSYS,XDB,ANONYMOUS,WKSYS,WKPROXY,ODM,\r\
\n\
ODM_MTR,\r\
\n\
OLAPSYS,\r\
\n\
RMAN,\r\
\n\
HR,\r\
\n\
OE,\r\
\n\
PM,\r\
\n\
SH,\r\
\n\
QS_ADM,\r\
\n\
QS,\r\
\n\
QS_WS,\r\
\n\
QS_ES,\r\
\n\
QS_OS,\r\
\n\
QS_CBADM,\r\
\n\
QS_CB,\r\
\n\
QS_CS,WMSYS,\r\
\n\
SYS,SYSTEM,OUTLN,SCOTT

sybase=master,model,sybsystemdb,sybsystemprocs,tempdb

