#UTF-8 처리

sqlserver=dtproperties,syscolumns,syscomments,sysdepends,sysfilegroups,sysfiles,\r\
\n\
sysfiles1,sysforeignkeys,sysfulltextcatalogs,sysfulltextnotify,sysindexes,\r\
\n\
sysindexkeys,sysmembers,sysobjects,syspermissions,sysproperties,sysprotects,\r\
\n\
sysreferences,systypes,sysusers

oracle=PLAN_TABLE

