#DL_P_RNMCNO=F{iiiiii-iM}
#DL_P_RNMCNO_VIEW=F{iiiiii-iM}

#주소, 상세주소 '*' 표시
#address1=F{I}
#address2=F{S}
#DNG_FLWG_ADDR=

#주민번호, 뒤 6자리 '*' 표시
#RNMCNO=F{iiiiii-iM}
#COL1=F{iiiiii-iM}

#계좌번호, 앞 4자리 '*' 표시

#RPT_GNL_AC_NO=F{mmmmI}

#신용카드번호, 가운데 2컬럼 '*' 표시
#cardno=F{iiii-mmmm-mmmm-iiii}

#여권번호, 뒷 5자리 '*' 표시
#COL10=B{Immmmm}

#운전면허번호, 뒷 5자리 '*' 표시
#driverno=F{ii-ii-iiimmm-mm}

#외국인등록번호, 뒷 6자리 '*' 표시
#foreinno=B{Immmmmm}

#핸드폰번호, 중간 4자리 '*' 표시
#COL8=F{iii-mmmm-iiii}

#전화번호, 중간 3자리 '*' 표시
#COL7=F{iii-ssss-iiii}

#이메일, 앞 3자리 '*' 표시
#email=F{mmmI}

#패스워드, 전체 '*' 표시
password=M

#RBA 샘플링
DATA05=F{iiiiii-iM}
DATA10=F{iiiiii-iM}

#주민번호, 뒤 6자리 '*' 표시
CS_NO=F{iiiiii-iM}
CS_NO_VIEW=F{iiiiii-iM}