#UTF-8 처리

WorkFlow=com.itplus.mm.server.workflow.impl.MMWorkFlow

JobDirAcl=com.itplus.mm.server.acl.impl.MMJobDirAcl

collectorClassName=com.itplus.mm.server.collector.CommonCollector

WorkItemClass.WFTG_W=com.itplus.mm.server.datadic.UTWWorkItem

WorkItemClass.WFTG_N=com.itplus.mm.server.datadic.UFWWorkItem

WorkItemClass.WFTG_D=com.itplus.mm.server.metamap.impl.MetaMapWorkItem

MenuAcl=com.itplus.mm.server.acl.impl.MMMenuAcl

