#UTF-8 처리
crosscheck.fieldMap.Table=TABLE_NAME=ENTITY_PHYSICAL_NAME

collector.req.afterDataProcess.query=mm.collector.req.attributeDeletedEntity.setWFGB_U

lnkinfo.Root.Child=Model,Schema,Application

lefttree.Category.Child=Source

crosscheck.field.PK=TABLE_NAME/PK_NAME

crosscheck.field.ModelPK=FN_GET_P_PHYSICAL_NAME(i.ELEM_INFO_ID) AS ::PHYSICAL_ENTITY_NAME

crosscheck.field.FK=FKTABLE_NAME/FK_NAME/PKTABLE_NAME

crosscheck.field.ModelFK=FN_GET_COL_PHYSICAL_NAMESPACE(i.ELEM_INFO_ID,'FKENTITY_ID') AS ::FKENTITY_NAME/FN_GET_COL_PHYSICAL_NAMESPACE(i.ELEM_INFO_ID,'PKENTITY_ID') AS ::PKENTITY_NAME/::PHYSICAL_FK_NAME

approval.uploadDir=/upload/metaminer/approval

crosscheck.field.SQLIndexColumn=TABLE_NAME/INDEX_NAME/COLUMN_NAME/ORDINAL_POSITION

ftp.uploadDir=upload/ftphost

lefttree.Application.Child=Category

initdata.uploadDir=upload/initdata

crosscheck.field.PKColumn=TABLE_NAME/PK_NAME/COLUMN_NAME/KEY_SEQ

crosscheck.field.View=TABLE_NAME

lnkinfo.Application.Child=Category

pk_fk_index=PK,FK,SQLIndex,ModelPK,ModelFK

lefttree.instancelist=Procedure,Table,Entity,Domain,ModelPK,ModelFK,PK,FK,View,SQLIndex,Source,Model,SubjectArea

lefttree.Root.Child=Model,Schema,Application

lefttree.ufw.leafnode=?????????????????????????????????????,????????????????????????

datstrc.elem.map.regist.item=Schema,Model,SubjectArea,Application,Category,Directory

crosscheck.field.ModelPKColumn=FN_GET_COL_PHYSICAL_NAMESPACE(i.ELEM_INFO_ID, 'ATTRIBUTE_ID') AS ::ATTRIBUTE_NAME

collector.executeBatch.count=5000

lefttree.Model=SubjectArea,Entity,Domain,ModelPK,ModelFK

metamap.uploadDir=metamap/upload/

crosscheck.field.Entity=LOGICAL_ENTITY_NAME/::PHYSICAL_ENTITY_NAME

csv.template.dir=CSV_TEMP

lefttree.Schema.Child=Table,PK,FK,SQLIndex,View,Procedure

linkInfo.uploadDir=upload/linkInfo

lefttree.VisibleElemRoot=Model,Schema,Application

crosscheck.field.SQLIndex=TABLE_NAME/INDEX_NAME

collector.afterDataProcess.query=mm.adapter.afterProcess.deleteColMap.byLinkInfo,mm.collector.after.delete.MM_ELEM_VAR_COL_MAP_TMP_4COL,\r\
\n\
mm.collector.after.insert.MM_ELEM_VAR_COL_MAP_TMP_4COL,mm.collector.after.insert.PK_YN,mm.adapter.afterProcess.insertIS_FK

lefttree.Schema=Table,PK,FK,View,SQLIndex,Procedure

crosscheck.field.FKColumn=FKTABLE_NAME/FK_NAME/FKCOLUMN_NAME/PKTABLE_NAME/PKCOLUMN_NAME

crosscheck.field.Column=TABLE_NAME/COLUMN_NAME/TYPE_NAME/COLUMN_SIZE/DECIMAL_DIGITS

crosscheck.field.Table=TABLE_NAME

crosscheck.field.ModelFKColumn=FN_GET_COL_PHYSICAL_NAMESPACE(i.ELEM_INFO_ID,'FKATTRIBUTE_ID') AS ::FKATTRIBUTE_NAME/FN_GET_COL_PHYSICAL_NAMESPACE(i.ELEM_INFO_ID,'PKATTRIBUTE_ID') AS ::PKATTRIBUTE_NAME

lefttree.Application=Category,Source

mm.adminRoleId=SuperUser

mm.trgtpcd.structure=BZTG_N

crosscheck.field.Procedure=PROCEDURE_NAME

lefttree.Model.Child=SubjectArea,Entity,ModelPK,ModelFK,Domain

lefttree.utw.leafnode=??????????????????????????,????????????????????????

crosscheck.Model=Entity,Attribute,ModelPK,ModelPKColumn,ModelFK,ModelFKColumn

crosscheck.field.Attribute=FN_GET_P_PHYSICAL_NAME(I.ELEM_INFO_ID) AS ::PHYSICAL_ENTITY_NAME/LOGICAL_ATTRIBUTE_NAME/::PHYSICAL_ATTRIBUTE_NAME/TYPE_NAME/COLUMN_SIZE/DECIMAL_DIGITS

process.uploadDir=upload/process

CommonCollector.autoCommit=1

lefttree.instanceelem=Schema,Model,SubjectArea,Application,Category

board.uploadDir=/upload/board

crosscheck.Schema=Table,Column,PK,PKColumn,FK,FKColumn,SQLIndex,SQLIndexColumn,Procedure,View

